// SPDX-License-Identifier: MIT
/* Copyright (c) 2026 Microchip Technology Inc. and its subsidiaries.
 * Microchip switch symbolic read tool
 *
 * License: MIT
 * Copyright (c) 2026 Microchip Technology Inc.
 */

#include <stdbool.h>
#include <stdint.h>
#include <sys/types.h>
#include <unistd.h>
#include <stdio.h>

#define BITS_PER_BYTE 8
#define BITS_PER_LONG (sizeof(long int)*BITS_PER_BYTE)

#define GENMASK(h, l) \
    (((~0UL) - (1UL << (l)) + 1) & (~0UL >> (BITS_PER_LONG - 1 - (h))))

#define SR_FLD_SET(v, h, l) ((v) << (l) & GENMASK((h), (l)))
#define SR_FLD_GET(v, h, l) (((v) & GENMASK((h), (l))) >> (l))
#define SR_FLD_MASK(h, l)   GENMASK((h), (l))

typedef uint32_t u32;
typedef uint64_t u64;

/* Short form to use in user defined operations */
#define rd sr_cmd_read
#define wr sr_cmd_write
#define pr printf
#define us usleep

typedef struct sr_io_s sr_io_t;

/* User defined operations */
typedef struct {
    char name[32];
    int  (*wait)(void);
    void (*signal)(void);
    void (*dump_mac)(void);
    void (*dump_vlan)(void);
    void (*dump_stream)(void);
    void (*dump_dd)(void);
    void (*dump_vcap)(u32 instance);
    sr_io_t* (*io_init)(void);
} sr_ops_t;

/********************************************************************************
 * Data structures for autogenerated register information
 *******************************************************************************/
typedef enum {
    SR_REG_ADDR_COMP_TGT,
    SR_REG_ADDR_COMP_GRP,
    SR_REG_ADDR_COMP_REG,
    SR_REG_ADDR_COMP_LAST,
} sr_reg_addr_comp_t;

typedef struct {
    const char *name;
    const uint width;
    const uint pos;
    const char *type;
} sr_fld_spec_t;

typedef struct {
    const uint cnt;
    const uint width;
    const off_t addr;
} sr_reg_addr_spec_t;

typedef struct {
    const char *name;
    const off_t tgt_offset;
    const sr_reg_addr_spec_t ra[SR_REG_ADDR_COMP_LAST];
    const sr_fld_spec_t *flds;
} sr_reg_spec_t;

/* symreg.c: */
u32 sr_cmd_read(char *addr);
void sr_cmd_write(char *addr, u32 value);

/* symreg_arg.c: */
typedef struct {
    bool address; /* Show addresses in dumps */
    uint base; /* Base to use in output: 2, 10 or 16 */
    bool force; /* Force write using wildcards without warning */
    bool nosem; /* Bypass semaphore */
    bool mac; /* Dump MAC table */
    bool vlan; /* Dump VLAN table */
    bool stream; /* Dump stream table */
    bool dd; /* Dump duplicate discard table */
    bool vcap; /* Dump VCAP table */
    u32 vcap_inst; /* VCAP instance to be dumped */
    bool raw; /* Read/Write in raw mode */
    char *argz;
    size_t argz_len;
} sr_arg_t;

int sr_arg_parse(int argc, char **argv, sr_arg_t *arg);

/* symreg_util.c: */
void *sr_zalloc(size_t size);
char *sr_strdup(const char *s);
void sr_strslice(const char *src, char *dst, size_t start, size_t end);
int sr_str2number(const char *str, long long *val, long long min, long long max);
int sr_str2u32(const char *str, u32 *val);

/* symreg_io.c: */
typedef u32 (*sr_io_read_t)(sr_io_t *io, int region, ulong addr);
typedef void (*sr_io_write_t)(sr_io_t *io, int region, ulong addr, u32 value);
typedef ulong (*sr_io_addr_t)(sr_io_t *io, int region, ulong addr);

typedef struct sr_io_s {
    sr_io_read_t read;
    sr_io_write_t write;
    sr_io_addr_t addr;
    ulong offset; /* io specific offset */
} sr_io_t;

int sr_io_close(sr_io_t *io);

sr_io_t *sr_io_pci_init(void);
sr_io_t *sr_io_sim_init(void);
sr_io_t *sr_io_fd_init(char *path);

/* vim: set ts=4 sw=4 sts=4 tw=120 cc=80,120 et ft=c cino=(0,w1,Ws,t0,\:s,l1 :*/
